# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions


name: Python Unit Test Runner

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt-get install python3-tk
        sudo apt-get install xvfb
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade pip
#        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    # Runs a single command using the runners shell
    - name: Execute all unit tests
      run: xvfb-run python3 -m unittest discover -s 'tests'


    # Runs a set of commands using the runners shell
    - name: Check test coverage
      run: |
        pip install coverage
        xvfb-run coverage run -m unittest discover -s 'tests'
        coverage report
        coverage html
    
    - name: Archive code coverage results
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: htmlcov